### ISSUE TITLE
Automatische Playerinstanz vom Typ Computer, wenn nur ein Mitspieler

### ISSUE THREAD

**Issue by Lucsaan** [Lucsaan/PlayGround#1]
Wenn nur ein Mitspieler ausgewählt wird, soll eine zusätzliche Instanz mit einem Namen und dem Typ Computer initialiert werden. 
Das ist wichtig, da man mindesten 2 Personen braucht zum spielen...

**Comment by Tweezzy** [comment]
Computer wird jetzt hinzugefügt wenn nur 1 Person eingeschrieben wurde.
